rodrigo-brito/ninjabot

pkg/notification/mail.go
Hey there,
Just want to added this feature. 
Feel free to close this PR if you don't want it.
=> Support for Mail as notification

.goreleaser.yml, examples/backtesting/main.go, examples/binance/main.go, examples/paperwallet/main.go, examples/strategies/emacross.go, examples/strategies/ocosell.go, ninjabot.go, pkg/ent/migrate/schema.go, pkg/ent/mutation.go, pkg/ent/order.go, pkg/ent/order/order.go, pkg/ent/order/where.go, pkg/ent/order_create.go, pkg/ent/order_update.go, pkg/ent/schema/order.go, pkg/exchange/binance.go, pkg/exchange/csvfeed.go, pkg/exchange/csvfeed_test.go, pkg/exchange/exchange.go, pkg/exchange/paperwallet.go, pkg/exchange/paperwallet_test.go, pkg/model/model.go, pkg/order/controller.go, pkg/order/controller_test.go, pkg/plot/assets/chart.html, pkg/plot/assets/chart.js, pkg/plot/chart.go, readme.md
- Include support for OCO orders in backtesting
- Fix date reference for limit / oco orders in plot
- Refactor examples directory
- Fix https://github.com/rodrigo-brito/ninjabot/issues/5
- Fix https://github.com/rodrigo-brito/ninjabot/issues/9
=> feat(backtesting): include OCO/Limit order support

.golangci.yml
golint is replaced by revive.  one small pull request to get started.
=> golint -> revive

.github/workflows/ci.yaml, exchange/binance.go, exchange/csvfeed.go, exchange/exchange.go, exchange/paperwallet.go, go.mod, go.sum, ninjabot.go, order/controller.go, service/service.go, strategy/controller.go
- Include backoff
- Fix payout and payoff calculation
=> fix(webscoket): include connection with backoff

.github/ISSUE_TEMPLATE.md/bug_report.md, .github/ISSUE_TEMPLATE.md/feature_request.md
=> added issue_template.md

order/feed_test.go
https://github.com/rodrigo-brito/ninjabot/issues/26
Added tests to feed modules
=> feat(test): add feed tests

model/model_test.go, model/priorityqueue_test.go, model/series_test.go
#30 
New tests on model package to improve coverage
=> feat(test): improving model test coverage

examples/backtesting/main.go, plot/indicator/bollingerbands.go
close #34
Added Bollinger Bands indicator.
=> feat(indicator): bollinger bands

examples/backtesting/main.go, exchange/paperwallet.go, exchange/paperwallet_test.go, ninjabot.go, ninjabot_test.go, plot/assets/chart.js, plot/chart.go
- Include max drow down in backtest results
- Merge bot results with wallet results
- Backtesting results automatic print the output
- Include max drow down in chart
Closes https://github.com/rodrigo-brito/ninjabot/issues/18
=> feat(backtest): include max draw down

examples/backtesting/main.go, exchange/binance.go, exchange/paperwallet.go, model/model.go, plot/indicator/stoch.go, plot/indicator/supertrend.go
- Include supertrend indicator
-  Include adition parameter for Stochastic indicator
=> feat(indicator): include supertrend indicator

exchange/paperwallet.go, exchange/paperwallet_test.go, plot/assets/chart.js, plot/chart.go
- Fix drawdown calculation
- Include drawdown annotation in chart result
=> fix(drawdown): fix drawdown calc and result plot

exchange/csvfeed.go, exchange/csvfeed_test.go, go.mod, go.sum
Ignore incomplete candles when resampling large timeframes.
=> fix(resample): skip imcomplete candles

plot/indicator/sma.go
What have you changed and why?
SMA indicator file is added
Related Issues
https://github.com/rodrigo-brito/ninjabot/issues/110
=> feat(plot) include SMA indicator

plot/indicator/willr.go
What have you changed and why?
Williams Percentage Range (%R) indicator file is added
Related Issues
https://github.com/rodrigo-brito/ninjabot/issues/110
=> feat(chart): include Williams %R indicator

exchange/binance.go, exchange/exchange.go, exchange/paperwallet.go, exchange/paperwallet_test.go, ninjabot.go, notification/telegram.go, order/controller.go
When trying to buy wrong quantity or non existent pair, the error shows us a little bit more:
Improved telegram error handling
https://github.com/rodrigo-brito/ninjabot/issues/88
=> Improve telegram error handling

.github/workflows/ci.yaml, exchange/binance.go, exchange/paperwallet.go, exchange/paperwallet_test.go, order/controller.go, readme.md, service/service.go
Include stop order for Binance and Paper Wallet
=> feat(exchange): include stop order

tools/scheduler.go
The order side in the BuyWhen function was wrong.
Close #204
=> fix(scheduler): wrong order side in BuyWhen

tools/trailing_test.go
Unity tests for tools/trailing.go.
Close #202
=> test(tools): TrailingStop

content/en/docs/storage/_index.md, content/en/docs/strategy/_index.md
Include docs for storage system
=> docs(storage): include storage section

download/download.go, download/download_test.go
there was a header that was removed from the toSlice() method of the candles and was still being passed as argument, so I removed it. 
closes https://github.com/rodrigo-brito/ninjabot/issues/212
let me know if there's anything else you need me to fix!
=> chore(csv): remove unused header

model/model.go, plot/chart.go, plot/indicator/bollingerbands.go, plot/indicator/cci.go, plot/indicator/ema.go, plot/indicator/macd.go, plot/indicator/obv.go, plot/indicator/rsi.go, plot/indicator/sma.go, plot/indicator/stoch.go, plot/indicator/supertrend.go, plot/indicator/willr.go, strategy/indicator.go
Include warmup settings for indicators
=> feat(chart): include warmup for indicators

model/series.go
Describe your changes here.
Link related issues here.
=> chore: fix function name

Makefile, exchange/binance.go, ninjabot.go, order/feed_test.go, plot/chart.go, storage/buntdb.go
Updating new issues found after update golangci-lint
=> fix: update lint rules

download/download.go
Describe your changes here.
Link related issues here.
=> fix: close recordFile

ninjabot.go
Describe your changes here.
https://github.com/rodrigo-brito/ninjabot/issues/332
=> fix: incorrect slice usage in Summary method

readme.md
Updated "sport and future markets" to "spot and futures market" to accurately describe the supported trading markets.
=> chore: correct typo in read.me description
